### ISSUE TITLE
Make emoji dep optional

### ISSUE THREAD

**Issue by J535D165** [earnestt1234/seedir#12]
Thanks for creating this rich-featured library. 

I think the natsort dependency is very welcome. However, the emoji dependency might not be needed by default. I think it can be made optional (like many libraries do in similar situations). This dependency doesn't support wheels :( What do you think?

**Comment by earnestt1234** [comment]
@J535D165 I had never considered this, but I am not opposed to it.  I pretty much agree - the emoji library is really only necessary for one printing style, and seedir should be totally functional without it.  I do need to google what a wheel is, however 😄 But if omitting emoji would be helpful for some use cases, that sounds good to me.

I think the changes would be:
- in `seedir.printing`, make the creation of `STYLE_DICT['emoji']` dependent on the `emoji` package being available
- add an informational error to `seedir.printing.get_styleargs()` when `'emoji'` is requested but not available
- remove emoji from the requirements in `setup.py`
- Add `extras_require={'emoji': ['emoji']}` to `setup.py`.  Then people should be able to `pip install seedir[emoji]`.
- Indicate this change in documentation.
- Rerun and update any test cases dependent on emoji.

I would also be open to making natsort be an optional dependency, so that seedir is otherwise all standard library.  But I don't feel strongly either way

**Comment by J535D165** [comment]
Nice outline of the changes needed. I think this is exactly what we need. 

I think natsort is lightweight and very well maintained. I don't think it will hurt anyone to keep this a dependency. 

And don't worry to much about the wheels. Your package has wheels on PyPI.

**Comment by earnestt1234** [comment]
Great - do you want to submit a pull request for this?  Otherwise I should be able to implement in the coming weeks.
