### ISSUE TITLE
Sorting capital letters before lowercase ones?

### ISSUE THREAD

**Issue by Ondrej-Sulc** [earnestt1234/seedir#14]
Hi, I ran into some sorting issues while using your library today.

While using "sort=True", It sorted the folder "COMPONENTS" before "Compensators" even though it should be the other way around. I fixed it by changing the folder name to "Components". I am guessing it's sorting the uppercase letters before the lowercase ones and it does not matter what's behind them. Is this intended behavior?

**Comment by earnestt1234** [comment]
@Ondrej-Sulc Thanks for the comment!  This is intended behavior, in so much as this is the typical behavior of sorting in Python:
```python
>>> sorted(['Zuchini', 'banana', 'apple'])
['Zuchini', 'apple', 'banana']
```
seedir actually uses [natsort](https://natsort.readthedocs.io/en/master/), rather than the built-in `sorted` , but the ranking of capital/lowercase letters does not change.  The intended way to get your desired output is to use `sort_key` when calling seedir.  I.e.:
```python
seedir.seedir('/your/path', sort_key = lambda x: x.lower())
```
It's the same idea as doing [case-insensitive sorting with `sorted`](https://stackoverflow.com/questions/13954841/https://stackoverflow.com/q/13954841/13386979).
