### ISSUE TITLE
Feature: Export to image

### ISSUE THREAD

**Issue by israteneda** [earnestt1234/seedir#2]
Amazing tool ✨

It'll be wonderful if it'll possible to export the file tree to image format to share with other people.

**Comment by earnestt1234** [comment]
@israteneda Interesting idea, let me look into how to do this.  My only concern is that this would have to include something like `PIL`, which may expand the dependencies a lot?  But at the very least I can try to do so and share my approach.  I'll look into it.

**Comment by earnestt1234** [comment]
@israteneda Here is an example which creates an image from the `str` output of `seedir`, based on [this example](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#example-draw-multiline-text) from `PIL`:
```python
# seedir
r = sd.randomdir(seed=5.69, extensions=['txt','pdf','jpg'])
s = r.seedir(printout=False)

# style
font = 'menlo.ttf' # path to font file
fontsize = 50
fontcolor = (0, 0, 0)
bg = (255, 255, 255)

# determine image size
split = [len(i) for i in s.split('\n')]
maxline = max(split)
w = int(maxline * fontsize * .7)
h = int(len(split) * fontsize * 1.2)

# create image and show
out = Image.new("RGB", (w, h), bg)
fnt = ImageFont.truetype(font, fontsize)
d = ImageDraw.Draw(out)
d.multiline_text((10,10), s, font=fnt, fill=fontcolor)

# showing
out.show()

# saving
# out.save('image.png')
```
The tricky part is determining the image size; I fooled around with different padding values based on the `fontsize`, and the above seemed to be working for most examples like this (i.e. similar `fontsize` and directory size).  You also (probably) want a monospace Unicode-supporting font - I used [Menlo](https://github.com/hbin/top-programming-fonts/raw/master/Menlo-Regular.ttf) which works nicely here but isn't working with the `"emoji"` style.

I might opt to not immediately add this, just because the above is finicky uses additional dependencies.  But if there are more requests or better implementations that can change.  Hopefully something like this can work for you in the interim?  I think this is a good example so thanks for raising.

**Comment by israteneda** [comment]
Thanks, @earnestt1234 for your answer and your efforts I appreciate it 🙏

I didn't know `PIL` neither I don't so fluent with python 😅 so my quick solution was to use [Carbon](https://carbon.now.sh/) for the image style and I copied the output of `seedir`.

Thanks for your explanation with the use of `PIL`. I'll try your approach on future needs.

![seedir-carbon](https://user-images.githubusercontent.com/20668624/103178071-b9186f00-484d-11eb-8b18-86f3dfea3421.png)

**Comment by earnestt1234** [comment]
@israteneda Well I wasn't familiar with Carbon, so thanks for sharing!  My output will stylistically not be as nice.  Plus the emoji style not working is a drawback (maybe this is the font I used? or a `PIL` issue?).  But it might be good if needing to make images for a bunch of `seedir.seedir()` calls.

`PIL` is (from what I gather) the main goto for working with images in Python.  There might be other options that will be better for this.  Seeing your image makes me think creating (nice) image outputs could be a good addition that fits with the spirit of the package.  So I will look into better ways to implement.

**Comment by danieldjewell** [comment]
@earnestt1234 It is very likely that the emojis weren't in the font. Most fonts don't have the glyphs for emojjs. Check out: https://github.com/ryanoasis/nerd-fonts

And yes, PIL is pretty much the goto for *raster* image editing. I would *highly* recommend implementing any drawing as a vector image (e.g. SVG) as it can be infinitely resized. Not sure the best way to do that here -- SVG itself is just XML...

Might also be worth checking out NetworkX ... I don't know that it would necessarily help with drawing (although it can interface with GraphViz ... ) but it might offer a way to store the tree info as a graph object that can then be more easily rendered.

**Comment by earnestt1234** [comment]
@danieldjewell thanks for you input!  I haven't seen the Nerd Fonts before, so I will consider that if I seriously try to implement it.

As for using SVG, I agree that would be a good way to go.  I have briefly looked at [`drawSvg`](https://github.com/cduck/drawSvg), which allows for SVG creation with a canvas, similar to `PIL`.  Though I haven't personally tried to use it, let alone for this purpose.

**Comment by earnestt1234** [comment]
Closing this for now as I haven't found a satisfying way to implement this, and I don't currently have plans to work on it more.
