### ISSUE TITLE
Can not handle `pathlib` objects

### ISSUE THREAD

**Issue by buhtzz** [earnestt1234/seedir#20]
As you can see here objects from `pathlib` are not recognized.

```
>>> import pathlib
>>> seedir.seedir(pathlib.Path.home() / 'target')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/seedir/realdir.py", line 336, in seedir
    s = RealDirStructure(path,
  File "/home/user/.local/lib/python3.9/site-packages/seedir/folderstructure.py", line 218, in __call__
    return self._folderstructure(folder, **kwargs).strip()
  File "/home/user/.local/lib/python3.9/site-packages/seedir/folderstructure.py", line 106, in _folderstructure
    self.getname(folder) +
  File "/home/user/.local/lib/python3.9/site-packages/seedir/folderstructure.py", line 226, in <lambda>
    getname_func = lambda x: os.path.basename(x.rstrip(slashes)),
AttributeError: 'PosixPath' object has no attribute 'rstrip'
```

**Comment by J535D165** [comment]
Facing the same issue. I think there are 2 ways to solve this in seedir:

- convert to string
- rework seedir to pathlib (best option imo, but lots of work)

**Comment by earnestt1234** [comment]
Thanks for raising this issue, sorry for the delayed response.  Yes, I was not very familiar with pathlib at the time of writing seedir, so seedir is generally ignorant of pathlib.  I looked into a little bit for the "FakeDir" portion, but ended up electing to implement my own classes.

I agree with @J535D165 about the options.  The immediate workaround is to convert to string on the user-end  e.g. `seedir.seedir(str(pathlib.Path.home())`.  And this would be my first thought to implement this within seedir - basically add a line that takes the input and converts it to an absolute, string path.  This would also knockout #19, other issue raise by OP.  From the user perspective, this would be enough to support pathlib objects, no?

OTOH, creating a pathlib implementation for `seedir.seedir()` would allow for arguments accepting callables to see pathlib objects instead of strings.  I.e. for `mask`, `sort_key`, and `formatter`, your function would see a `pathlib.Path` instead of a string path.  I could see this being desirable for some of the convenient attributes / methods already implemented by pathlib.  I don't think this would be too hard to implement (maybe a little tedious) - it would basically involve creating an instance of the `seedir.folderstructure.FolderStructure()` class with functions for pathlib objects, e.g. a `PathlibStructure`.  Would be defined here, similar to what has been done for strings and FakeDirs:

https://github.com/earnestt1234/seedir/blob/ec506ca6fd1a141aca5407cb56e2a12d0ffbf782/seedir/folderstructure.py#L222-L240

My suggestion would be to implement this and then add an option to `seedir.seedir()` which selects either the existing string interface or the new pathlib one, e.g.  `seedir.seedir(mode='string')` or `seedir.seedir(mode='pathlib')`.  Or it could automatically be set based on what sort of object the user passes.

**Comment by earnestt1234** [comment]
This feature has been added in version [0.4.0](https://github.com/earnestt1234/seedir/releases/tag/v0.4.0):
```python
>>> import pathlib
>>> import seedir as sd

>>> sd.seedir(pathlib.Path.home() / 'Desktop', itemlimit=2)
Desktop/
├─.DS_Store
└─.localized
```

**Comment by earnestt1234** [comment]
And in regards to my initial (long) comment, the process of applying seedir to new object types has been made easier; [an example has been added to the docs](https://earnestt1234.github.io/seedir/seedir/index.html#extending-seedir).

**Comment by J535D165** [comment]
Nice!
